# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ideasxdevice.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IdeasXDevice(object):
    def setupUi(self, IdeasXDevice):
        IdeasXDevice.setObjectName("IdeasXDevice")
        IdeasXDevice.resize(506, 84)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(IdeasXDevice.sizePolicy().hasHeightForWidth())
        IdeasXDevice.setSizePolicy(sizePolicy)
        IdeasXDevice.setMinimumSize(QtCore.QSize(452, 84))
        IdeasXDevice.setMaximumSize(QtCore.QSize(16777215, 84))
        IdeasXDevice.setAcceptDrops(False)
        IdeasXDevice.setAutoFillBackground(False)
        self.horizontalLayout = QtWidgets.QHBoxLayout(IdeasXDevice)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widgetInfo = QtWidgets.QWidget(IdeasXDevice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetInfo.sizePolicy().hasHeightForWidth())
        self.widgetInfo.setSizePolicy(sizePolicy)
        self.widgetInfo.setMinimumSize(QtCore.QSize(290, 66))
        self.widgetInfo.setObjectName("widgetInfo")
        self.label = QtWidgets.QLabel(self.widgetInfo)
        self.label.setGeometry(QtCore.QRect(4, 5, 90, 60))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./icon/devicetype/modulev3.png"))
        self.label.setObjectName("label")
        self.labelRSSI = QtWidgets.QLabel(self.widgetInfo)
        self.labelRSSI.setGeometry(QtCore.QRect(100, 50, 86, 16))
        self.labelRSSI.setObjectName("labelRSSI")
        self.labelModuleID = QtWidgets.QLabel(self.widgetInfo)
        self.labelModuleID.setGeometry(QtCore.QRect(100, 0, 231, 35))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed")
        font.setPointSize(20)
        font.setItalic(False)
        self.labelModuleID.setFont(font)
        self.labelModuleID.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelModuleID.setObjectName("labelModuleID")
        self.labelBattery = QtWidgets.QLabel(self.widgetInfo)
        self.labelBattery.setGeometry(QtCore.QRect(100, 35, 166, 16))
        self.labelBattery.setObjectName("labelBattery")
        self.horizontalLayout.addWidget(self.widgetInfo)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.widgetControls = QtWidgets.QWidget(IdeasXDevice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetControls.sizePolicy().hasHeightForWidth())
        self.widgetControls.setSizePolicy(sizePolicy)
        self.widgetControls.setMinimumSize(QtCore.QSize(120, 66))
        self.widgetControls.setMaximumSize(QtCore.QSize(120, 66))
        self.widgetControls.setObjectName("widgetControls")
        self.labelStatus = QtWidgets.QLabel(self.widgetControls)
        self.labelStatus.setGeometry(QtCore.QRect(-5, 55, 116, 10))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setItalic(True)
        self.labelStatus.setFont(font)
        self.labelStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelStatus.setObjectName("labelStatus")
        self.buttonMenu = QtWidgets.QToolButton(self.widgetControls)
        self.buttonMenu.setGeometry(QtCore.QRect(95, 10, 21, 36))
        self.buttonMenu.setAutoRaise(False)
        self.buttonMenu.setArrowType(QtCore.Qt.DownArrow)
        self.buttonMenu.setObjectName("buttonMenu")
        self.buttonActivate = QtWidgets.QToolButton(self.widgetControls)
        self.buttonActivate.setGeometry(QtCore.QRect(5, 10, 91, 36))
        self.buttonActivate.setCheckable(True)
        self.buttonActivate.setAutoRaise(False)
        self.buttonActivate.setObjectName("buttonActivate")
        self.horizontalLayout.addWidget(self.widgetControls)

        self.retranslateUi(IdeasXDevice)
        QtCore.QMetaObject.connectSlotsByName(IdeasXDevice)

    def retranslateUi(self, IdeasXDevice):
        _translate = QtCore.QCoreApplication.translate
        IdeasXDevice.setWindowTitle(_translate("IdeasXDevice", "Form"))
        self.labelRSSI.setText(_translate("IdeasXDevice", "RSSI:  -54dBm"))
        self.labelModuleID.setText(_translate("IdeasXDevice", "2f:32:56:4f:72:d8"))
        self.labelBattery.setText(_translate("IdeasXDevice", "Battery:  98%"))
        self.labelStatus.setText(_translate("IdeasXDevice", "Last Update: 2:30AM"))
        self.buttonMenu.setText(_translate("IdeasXDevice", "Activate "))
        self.buttonActivate.setText(_translate("IdeasXDevice", "Activate"))

