# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(415, 459)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(True)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.VerticalTabs)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabEncoder = QtWidgets.QWidget()
        self.tabEncoder.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabEncoder.setObjectName("tabEncoder")
        self.gridLayout = QtWidgets.QGridLayout(self.tabEncoder)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.searchEncoder = QtWidgets.QLineEdit(self.tabEncoder)
        self.searchEncoder.setClearButtonEnabled(True)
        self.searchEncoder.setObjectName("searchEncoder")
        self.gridLayout.addWidget(self.searchEncoder, 1, 1, 1, 1)
        self.tableEncoder = QtWidgets.QTableView(self.tabEncoder)
        self.tableEncoder.setEnabled(True)
        self.tableEncoder.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableEncoder.setAlternatingRowColors(True)
        self.tableEncoder.setShowGrid(False)
        self.tableEncoder.setGridStyle(QtCore.Qt.NoPen)
        self.tableEncoder.setSortingEnabled(True)
        self.tableEncoder.setObjectName("tableEncoder")
        self.tableEncoder.horizontalHeader().setStretchLastSection(True)
        self.tableEncoder.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableEncoder, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tabEncoder, "")
        self.tabActuator = QtWidgets.QWidget()
        self.tabActuator.setObjectName("tabActuator")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabActuator)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.searchActuator = QtWidgets.QLineEdit(self.tabActuator)
        self.searchActuator.setAutoFillBackground(False)
        self.searchActuator.setFrame(True)
        self.searchActuator.setClearButtonEnabled(True)
        self.searchActuator.setObjectName("searchActuator")
        self.gridLayout_2.addWidget(self.searchActuator, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.tableActuator = QtWidgets.QTableView(self.tabActuator)
        self.tableActuator.setEnabled(True)
        self.tableActuator.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableActuator.setAlternatingRowColors(True)
        self.tableActuator.setShowGrid(False)
        self.tableActuator.setSortingEnabled(True)
        self.tableActuator.setObjectName("tableActuator")
        self.tableActuator.horizontalHeader().setStretchLastSection(True)
        self.tableActuator.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.tableActuator, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tabActuator, "")
        self.tabSetting = QtWidgets.QWidget()
        self.tabSetting.setObjectName("tabSetting")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabSetting)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelPassword = QtWidgets.QLabel(self.tabSetting)
        self.labelPassword.setObjectName("labelPassword")
        self.gridLayout_4.addWidget(self.labelPassword, 9, 0, 1, 1)
        self.wifiPassword = QtWidgets.QLineEdit(self.tabSetting)
        self.wifiPassword.setObjectName("wifiPassword")
        self.gridLayout_4.addWidget(self.wifiPassword, 9, 1, 1, 2)
        self.labelNetworkBroker = QtWidgets.QLabel(self.tabSetting)
        self.labelNetworkBroker.setObjectName("labelNetworkBroker")
        self.gridLayout_4.addWidget(self.labelNetworkBroker, 1, 0, 1, 1)
        self.localBroker = QtWidgets.QLineEdit(self.tabSetting)
        self.localBroker.setObjectName("localBroker")
        self.gridLayout_4.addWidget(self.localBroker, 3, 1, 1, 2)
        self.networkBroker = QtWidgets.QLineEdit(self.tabSetting)
        self.networkBroker.setObjectName("networkBroker")
        self.gridLayout_4.addWidget(self.networkBroker, 1, 1, 1, 2)
        self.labelSSID = QtWidgets.QLabel(self.tabSetting)
        self.labelSSID.setObjectName("labelSSID")
        self.gridLayout_4.addWidget(self.labelSSID, 8, 0, 1, 1)
        self.localPort = QtWidgets.QLineEdit(self.tabSetting)
        self.localPort.setObjectName("localPort")
        self.gridLayout_4.addWidget(self.localPort, 4, 1, 1, 2)
        self.wifiSSID = QtWidgets.QLineEdit(self.tabSetting)
        self.wifiSSID.setObjectName("wifiSSID")
        self.gridLayout_4.addWidget(self.wifiSSID, 8, 1, 1, 2)
        self.labelAPSelector = QtWidgets.QLabel(self.tabSetting)
        self.labelAPSelector.setObjectName("labelAPSelector")
        self.gridLayout_4.addWidget(self.labelAPSelector, 7, 0, 1, 1)
        self.networkPort = QtWidgets.QLineEdit(self.tabSetting)
        self.networkPort.setText("")
        self.networkPort.setObjectName("networkPort")
        self.gridLayout_4.addWidget(self.networkPort, 2, 1, 1, 2)
        self.selectAP = QtWidgets.QSpinBox(self.tabSetting)
        self.selectAP.setSuffix("")
        self.selectAP.setMinimum(1)
        self.selectAP.setMaximum(5)
        self.selectAP.setObjectName("selectAP")
        self.gridLayout_4.addWidget(self.selectAP, 7, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 6, 0, 1, 2)
        self.labelLocalBroker = QtWidgets.QLabel(self.tabSetting)
        self.labelLocalBroker.setObjectName("labelLocalBroker")
        self.gridLayout_4.addWidget(self.labelLocalBroker, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 7, 2, 1, 1)
        self.buttonTrainDevice = QtWidgets.QPushButton(self.tabSetting)
        self.buttonTrainDevice.setObjectName("buttonTrainDevice")
        self.gridLayout_4.addWidget(self.buttonTrainDevice, 10, 2, 1, 1)
        self.buttonSettings = QtWidgets.QPushButton(self.tabSetting)
        self.buttonSettings.setObjectName("buttonSettings")
        self.gridLayout_4.addWidget(self.buttonSettings, 5, 2, 1, 1)
        self.tabWidget.addTab(self.tabSetting, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "IdeasX Workstation Client"))
        self.searchEncoder.setPlaceholderText(_translate("MainWindow", "Search for Encoder by Username or Device ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEncoder), _translate("MainWindow", "Encoders"))
        self.searchActuator.setPlaceholderText(_translate("MainWindow", "Search for Actuator by Name or Device ID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabActuator), _translate("MainWindow", "Actuators"))
        self.labelPassword.setText(_translate("MainWindow", "Password:"))
        self.labelNetworkBroker.setText(_translate("MainWindow", "Network Broker:"))
        self.localBroker.setPlaceholderText(_translate("MainWindow", "URL or IP"))
        self.networkBroker.setPlaceholderText(_translate("MainWindow", "URL or IP"))
        self.labelSSID.setText(_translate("MainWindow", "SSID:"))
        self.localPort.setPlaceholderText(_translate("MainWindow", "Port"))
        self.labelAPSelector.setText(_translate("MainWindow", "Wi-Fi Access Point:"))
        self.networkPort.setPlaceholderText(_translate("MainWindow", "Port"))
        self.selectAP.setPrefix(_translate("MainWindow", "AP "))
        self.labelLocalBroker.setText(_translate("MainWindow", "Local Broker:"))
        self.buttonTrainDevice.setText(_translate("MainWindow", "Train IdeasX Device"))
        self.buttonSettings.setText(_translate("MainWindow", "Apply Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSetting), _translate("MainWindow", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

